USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS {DATABASE_NAME}
    COMMENT = 'Marketing production CRM database with private access.';


USE ROLE SECURITYADMIN;

-- Create functional roles to manage the database
CREATE OR REPLACE ROLE RL_{DATABASE_NAME}_ADMIN;

-- Grant the role to the proper user
GRANT ROLE RL_{DATABASE_NAME}_ADMIN TO USER MKEETER;

-- Platform admin changes ownership to the DB_ADMIN role
GRANT OWNERSHIP ON DATABASE {DATABASE_NAME} TO ROLE RL_{DATABASE_NAME}_ADMIN;

-- Create Database Roles
USE ROLE RL_{DATABASE_NAME}_ADMIN;
USE DATABASE {DATABASE_NAME};

CREATE OR REPLACE DATABASE ROLE DB_R_DBR_{DATABASE_NAME}; -- read
CREATE OR REPLACE DATABASE ROLE DB_C_DBR_{DATABASE_NAME}; -- create
CREATE OR REPLACE DATABASE ROLE DB_W_DBR_{DATABASE_NAME}; -- write

SHOW DATABASE ROLES IN DATABASE {DATABASE_NAME};


-- Grant database permissions to database roles
GRANT USAGE ON DATABASE {DATABASE_NAME} TO DATABASE ROLE DB_R_DBR_{DATABASE_NAME};
GRANT CREATE SCHEMA ON DATABASE {DATABASE_NAME} TO DATABASE ROLE DB_C_DBR_{DATABASE_NAME};
GRANT ALL ON DATABASE {DATABASE_NAME} TO DATABASE ROLE DB_W_DBR_{DATABASE_NAME};

-- Create a Managed Access Schema
USE ROLE RL_{DATABASE_NAME}_ADMIN;

CREATE OR REPLACE SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} WITH MANAGED ACCESS;

SHOW GRANTS ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME};



-- Create schema access roles using database roles
USE ROLE RL_{DATABASE_NAME}_ADMIN;

-- Create Schema access roles using database roles
CREATE OR REPLACE DATABASE ROLE SC_R_DBR_{DATABASE_NAME};
CREATE OR REPLACE DATABASE ROLE SC_C_DBR_{DATABASE_NAME};
CREATE OR REPLACE DATABASE ROLE SC_W_DBR_{DATABASE_NAME};


-- Schema Object Grants
-- Read Only
GRANT USAGE ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} TO DATABASE ROLE SC_R_DBR_{DATABASE_NAME};
GRANT SELECT ON ALL TABLES IN SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} TO DATABASE ROLE SC_R_DBR_{DATABASE_NAME};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} TO DATABASE ROLE SC_R_DBR_{DATABASE_NAME};

-- create any object
GRANT ALL ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} TO DATABASE ROLE SC_C_DBR_{DATABASE_NAME};
REVOKE MODIFY ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} FROM DATABASE ROLE SC_C_DBR_{DATABASE_NAME};

-- write (allows renaming the schema)
GRANT ALL ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME} TO DATABASE ROLE SC_W_DBR_{DATABASE_NAME};

-- inheritance
GRANT DATABASE ROLE SC_R_DBR_{DATABASE_NAME} TO DATABASE ROLE SC_C_DBR_{DATABASE_NAME};
GRANT DATABASE ROLE SC_C_DBR_{DATABASE_NAME} TO DATABASE ROLE SC_W_DBR_{DATABASE_NAME};

SHOW GRANTS ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME};

-- grant database role to schema roles
USE ROLE RL_{DATABASE_NAME}_ADMIN;

GRANT DATABASE ROLE DB_R_DBR_{DATABASE_NAME} TO DATABASE ROLE SC_R_DBR_{DATABASE_NAME};
GRANT DATABASE ROLE DB_R_DBR_{DATABASE_NAME} TO DATABASE ROLE SC_C_DBR_{DATABASE_NAME};
GRANT DATABASE ROLE DB_R_DBR_{DATABASE_NAME} TO DATABASE ROLE SC_W_DBR_{DATABASE_NAME};


-- Create account level roles
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE {DATABASE_NAME}_ANALYST;
CREATE OR REPLACE ROLE {DATABASE_NAME}_DEVELOPER;
CREATE OR REPLACE ROLE {DATABASE_NAME}_SUPPORT;

-- GRANT ROLE {DATABASE_NAME}_ANALYST TO USER MKEETER;
-- GRANT ROLE {DATABASE_NAME}_DEVELOPER TO USER MKEETER;
-- GRANT ROLE {DATABASE_NAME}_SUPPORT TO USER MKEETER;

SHOW GRANTS ON DATABASE {DATABASE_NAME};
SHOW GRANTS ON SCHEMA {DATABASE_NAME}.{SCHEMA_NAME};


-- =========================================================
-- EXAMPLES
-- =========================================================

-- You cannot grant Database Roles to users
GRANT ROLE DB_R_DBR_{DATABASE_NAME} TO USER MKEETER;

-- You cannot create an Account Level Role with your Database Role
USE ROLE RL_{DATABASE_NAME}_ADMIN;
CREATE ROLE SUPER_USER_123;

-- You cannot grant an Account Role to a Database Role
-- The database role scope is only within the DB
GRANT ROLE SYSADMIN TO DATABASE ROLE DB_R_DBR_{DATABASE_NAME};
